chore: run cargo fmt and refresh CLI tooling

diff --git a/claudine/justfile b/claudine/justfile
--- a/claudine/justfile
+++ b/claudine/justfile
@@ -1,7 +1,24 @@
 set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
 
 BOLD := '\033[1m'
+DIM := '\033[2m'
+ITALIC := '\033[3m'
 RESET := '\033[0m'
+RED := '\033[31m'
+GREEN := '\033[32m'
+YELLOW := '\033[33m'
+BLUE := '\033[34m'
+MAGENTA := '\033[35m'
+CYAN := '\033[36m'
+
+PACKAGE := "Claudine"
+LIB_NAME := PACKAGE + " Library"
+CLI_NAME := PACKAGE + " CLI"
+LIBRARY := lowercase(PACKAGE)
+CLI := lowercase(PACKAGE) + "-cli"
+CLI_PATH := "./cli"
+DOCS := ""
+
 
 default:
     #!/usr/bin/env bash
@@ -12,84 +29,198 @@ default:
     fi
 
     echo
-    echo "Claudine (Library & CLI)"
-    echo "========================"
+    echo -e "{{BOLD}}{{PACKAGE}} ({{RESET}}Library & CLI{{BOLD}}){{RESET}}"
+    echo "======================================================================================"
     echo ""
     just --list | grep -v 'default'
     echo
 
+# Uses TTS if available but never error
+_speak *args:
+    @so-you-say "{{args}}" --background >/dev/null 2>&1 || exit 0
+
+# Ask Claude Code in a non-interactive session
+_claude PROMPT:
+    @unset ANTHROPIC_API_KEY && cd .. && claude --dangerously-skip-permissions -p \'{{PROMPT}}\'
+
+# Ask Claude Code via a prompt file in a non-interactive session
+_claude_file PROMPT_FILE:
+    @unset ANTHROPIC_API_KEY && cd .. && claude --dangerously-skip-permissions -p "$(cat {{PROMPT_FILE}})"
+
 # Build the library and CLI
 build *args="":
-    cargo build -p claudine -p claudine-cli {{args}}
+    @echo -e "Building {{LIB_NAME}}"
+    @echo
+    cargo build -p {{LIBRARY}} {{args}} || ( just _speak "The {{LIB_NAME}} build failed!" && echo -e "\n❌ The {{LIB_NAME}} build failed!" && exit 1)
+    @echo
+    @echo -e "✅ {{BOLD}}{{LIB_NAME}}{{RESET}} built successfully"
+    @echo
+    @echo -e "Building {{BOLD}}{{CLI_NAME}}{{RESET}}"
+    @echo
+    cargo build -p {{CLI}} {{args}} || ( just _speak "The {{CLI_NAME}} build failed!" && echo -e "\n❌ The {{CLI_NAME}} build failed!" && exit 1)
+    @echo
+    @echo -e "✅ {{BOLD}}{{CLI_NAME}}{{RESET}} built successfully"
+    @echo
 
 # Test both library and CLI
 test:
-    cargo test -p claudine -p claudine-cli
+    @echo
+    @echo -e "Testing {{BOLD}}{{LIB_NAME}}{{RESET}}"
+    @echo
+    cargo test -p {{LIBRARY}} || ( just _speak "The {{LIB_NAME}} has failing tests" && echo -e "\n❌ The {{BOLD}}{{RED}}{{LIB_NAME}}{{RESET}} has failing tests!" && exit 1 )
+    @echo
+    @echo -e "✅ {{BOLD}}{{GREEN}}{{LIB_NAME}} has passed all tests{{RESET}}"
+    @echo -e "Testing {{BOLD}}{{CLI_NAME}}{{RESET}}"
+    @echo
+    cargo test -p "{{CLI}}" || ( just _speak "The {{CLI_NAME}} has failing tests" && echo -e "\n❌ The {{BOLD}}{{RED}}{{CLI_NAME}}{{RESET}} has failing tests!" )
+    @echo
+    @echo -e "✅ {{BOLD}}{{GREEN}}{{CLI_NAME}} has passed all tests{{RESET}}"
 
 # Lint both the library and CLI
 lint:
-    cargo clippy -p claudine -p claudine-cli
+    @echo
+    @echo -e "Linting {{BOLD}}{{LIB_NAME}}{{RESET}}"
+    @echo
+    @cargo clippy -p {{LIBRARY}} -- -D warnings || ( just _speak "The {{LIB_NAME}} has failing lints" && echo -e "\n❌ The {{BOLD}}{{RED}}{{LIB_NAME}}{{RESET}} has failing lints!" && exit 1 )
+    @echo
+    @echo -e "Linting {{BOLD}}{{CLI_NAME}}{{RESET}}"
+    @echo
+    @cargo clippy -p {{CLI}} -- -D warnings || ( just _speak "The {{CLI_NAME}} has failing lints" && echo -e "\n❌ The {{BOLD}}{{RED}}{{CLI_NAME}}{{RESET}} has failing lints!" && exit 1)
 
 # Lint (and fix) both the library and CLI
-lint-fix *args="":
-    cargo clippy --fix -p claudine -p claudine-cli {{args}}
+lint-fix:
+    @echo
+    @echo -e "Linting ({{ITALIC}}with fixes{{RESET}}) {{BOLD}}{{LIB_NAME}}{{RESET}}"
+    @echo
+    @cargo clippy --fix -p {{LIBRARY}} -- -D warnings || ( just _speak "The {{LIB_NAME}} has failing lints even after attempt to autofix" && echo -e "\n❌ The {{BOLD}}{{RED}}{{LIB_NAME}}{{RESET}} has failing lints!" && exit 1 )
+    @echo
+    @echo -e "Linting ({{ITALIC}}with fixes{{RESET}}) {{BOLD}}{{CLI_NAME}}{{RESET}}"
+    @echo
+    cargo clippy --fix -p {{CLI}} -- -D warnings || ( just _speak "The {{CLI_NAME}} has failing lints" && echo -e "\n❌ The {{BOLD}}{{RED}}{{CLI_NAME}}{{RESET}} has failing lints!" && exit 1)
+
+_lint_fix_library ERR_FILE:
+    @echo -e "❌ {{RED}}Errors{{RESET}} {{ITALIC}}were{{RESET}} found in {{BOLD}}{{LIB_NAME}}{{RESET}}; kicking off AI to fix.\n"
+    @echo "/{{LIBRARY}} Fix the lint errors in {{LIB_NAME}}:" > "/tmp/{{LIBRARY}}_claude_prompt.txt"
+    @echo "" >> "/tmp/{{LIBRARY}}_claude_prompt.txt"
+    @cat {{ERR_FILE}} >> "/tmp/{{LIBRARY}}_claude_prompt.txt"
+    @just _claude_file "/tmp/{{LIBRARY}}_claude_prompt.txt" || ( so-you-say "claude code was unable to fix the lint errors" | exit 1 )
+    @echo -e "\n🎉 Claude Code believes all lint errors in {{BOLD}}{{LIB_NAME}}{{RESET}} are now fixed"
+    @just _speak "Claude Code believes it has fixed all lint errors in {{LIB_NAME}}"
+    @cargo clippy -p {{LIBRARY}} -- -D warnings 2> "/tmp/{{LIBRARY}}_clippy_errors.txt" || ( so-you-say "it appears that claude code did NOT remove all the lint errors in {{LIB_NAME}}" && exit 1)
+
+_lint_fix_cli ERR_FILE:
+    @echo -e "❌ {{RED}}Errors{{RESET}} {{ITALIC}}were{{RESET}} found in {{BOLD}}{{CLI_NAME}}{{RESET}}; kicking off AI to fix.\n"
+    @echo "/{{CLI}} Fix the lint errors in {{CLI_NAME}}:" > "/tmp/{{CLI}}_claude_prompt.txt"
+    @echo "" >> "/tmp/{{CLI}}_claude_prompt.txt"
+    @cat {{ERR_FILE}} >> "/tmp/{{CLI}}_claude_prompt.txt"
+    @just _claude_file "/tmp/{{CLI}}_claude_prompt.txt" || ( so-you-say "claude code was unable to fix the lint errors" | exit 1 )
+    @echo -e "\n🎉 Claude Code believes all lint errors in {{BOLD}}{{CLI_NAME}}{{RESET}} are now fixed"
+    @just _speak "Claude Code believes it has fixed all lint errors in {{CLI_NAME}}"
+    @cargo clippy -p {{CLI}} -- -D warnings 2> "/tmp/{{CLI}}_clippy_errors.txt" || ( so-you-say "it appears that claude code did NOT remove all the lint errors in {{LIB_NAME}}" && exit 1)
+    @echo -e "✅ It has been confirmed that all lint errors in {{BOLD}}{{CLI_NAME}}{{RESET}} have been fixed"
+
+# Fix lint errors with AI
+lint-fix-ai:
+    @echo
+    @echo -e "Checking {{BOLD}}{{LIB_NAME}}{{RESET}} for lint errors"
+    @cargo clippy -p {{LIBRARY}} -- -D warnings 2> "/tmp/{{LIBRARY}}_clippy_errors.txt" || just _lint_fix_library "/tmp/{{LIBRARY}}_clippy_errors.txt"
+    @echo -e "✅ No lint errors in {{BOLD}}{{LIB_NAME}}{{RESET}}"
+    @echo
+    @echo -e "Checking {{BOLD}}{{CLI_NAME}}{{RESET}} for lint errors"
+    @cargo clippy -p {{CLI}} -- -D warnings 2> "/tmp/{{CLI}}_clippy_errors.txt" || just _lint_fix_cli "/tmp/{{CLI}}_clippy_errors.txt"
+    @echo -e "✅ No lint errors in {{BOLD}}{{CLI_NAME}}{{RESET}}"
+    @just _speak "No lint errors were found in {{PACKAGE}}"
 
 # commits all the staged changes using GPT 5.2 (via Opencode)
 commit:
-    @echo "Committing staged changes in the Rusty Biscuit monorepo to git"
+    @echo ""
+    @echo -e "Committing staged changes in the {{BOLD}}Rusty Biscuit{{RESET}} monorepo to git"
     @echo ""
     @opencode run commit "-f" --model "openai/gpt-5.2"
     @if command -v so-you-say >/dev/null 2>&1; then \
         so-you-say "git commits completed in rusty-biscuit monorepo"; \
     fi
 
-# Install the Claudine CLI
-install:
-    @echo ""
-    @echo -e "{{BOLD}}Building Claudine Library{{RESET}}"
-    @echo ""
-    @cargo build -p claudine --release  || ( playa effect error-2 2>/dev/null && exit 1 )
-    @echo ""
-    @echo -e "{{BOLD}}{{YELLOW}}Installing Claudine CLI{{RESET}}"
-    @cargo install --path ./cli  || ( playa effect error-2 2>/dev/null && exit 1 )
+# Install the CLI
+install *args="":
+    @echo
+    @echo -e "{{BOLD}}Building {{LIB_NAME}}{{RESET}}"
+    @echo
+    @cargo build -p {{LIBRARY}} --release  || ( playa effect error-2 2>/dev/null && exit 1 )
+    @echo
+    @echo -e "{{BOLD}}{{YELLOW}}Installing {{CLI_NAME}}{{RESET}}"
+    @echo
+    @cargo install --path {{CLI_PATH}} {{args}} || ( playa effect error-2 2>/dev/null && exit 1 )
+    @echo "{{BOLD}}{{BLUE}}{{CLI_NAME}} installed{{RESET}}"
+    @playa effect drop-4 2>/dev/null || return 0
 
 # Validate the source code without doing a full build
 check:
-    @cargo check -p claudine -p claudine-cli
+    @cargo check -p {{LIBRARY}} -p {{CLI}}
 
 # Run the latest debug build of the Claudine CLI
 cli *args="":
-    @cargo run -p claudine-cli {{args}}
+    @cargo run -p {{CLI}} {{args}}
 
 # Open Claude Code in yolo mode
 oc *args="":
     @clear
-    @echo "Loading {{BOLD}}Opencode{{RESET}}"
+    @echo -e "Loading {{BOLD}}Opencode{{RESET}}"
     @cd .. && opencode {{args}}
 
 # Open Opencode
 cc *args="":
     @clear
-    @echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
+    @echo -e "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
     @cd .. && claude --dangerously-skip-permissions {{args}}
 
 # Open Codex CLI
 codex *args="":
     @clear
-    @echo "Loading {{BOLD}}Codex CLI{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
+    @echo -e "Loading {{BOLD}}Codex CLI{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
     @cd .. && codex --dangerously-bypass-approvals-and-sandbox {{args}}
 
 # Show the dependencies for this package
 deps:
     @echo "Dependencies:"
-    @echo "$(just -f ../justfile repo-deps 2>/dev/null)" | rg "claudine"
+    @echo "$(just -f ../justfile repo-deps 2>/dev/null)" | rg "{{LIBRARY}}*:"
+
+readme_files:
+    @sniff docs --readme --json | jq -r '[.[] | select(.relative | startswith("{{LIBRARY}}")) | "@" + .relative ] | join(" ")'
 
 # review this package using the Codex CLI
 review *args="":
     @clear
-    @echo -e "Performing a code review on the {{BOLD}}Claudine{{RESET}} package"
+    @echo -e "Performing a code review on the {{BOLD}}{{LIB_NAME}}{{RESET}} package"
     @echo ""
-    @cd .. && codex exec "/code-review the code in the Claudine package; use the rust, claudine, biscuit-terminal, and clap skills during the review. Write your findings to the file '@claudine/docs/{YYYY}-{MM}. claudine-review.md' (where YYYY is the current year, and MM is the current month)." "$(just deps)" {{args}} || ( so-you-say "There was a problem running the code review in the claudine package" >/dev/null 2>&1 && echo -e "{RED}ERROR:{RESET}: problems with the claudine review."  && exit 1 )
-    @so-you-say "Review for claudine package has completed." >/dev/null 2>&1 || exit 0
+    @cd .. && codex exec "/code-review the code in the {{LIB_NAME}} package; use the rust, {{LIBRARY}}, biscuit-terminal, and clap skills during the review. Write your findings to the file '@{{LIBRARY}}/docs/{YYYY}-{MM}. {{LIBRARY}}-review.md' (where YYYY is the current year, and MM is the current month).\n\n$(just deps)\n\n{{args}}"  || ( so-you-say "There was a problem running the code review in the {{LIB_NAME}} package" >/dev/null 2>&1 && echo -e "{RED}ERROR:{RESET}: problems with the {{LIB_NAME}} review."  && exit 1 )
+    @echo
+    @echo -e "Code Review for the {{BLUE}}{{LIB_NAME}}{{RESET}} package has completed"
+    @just _speak "Review for {{LIB_NAME}} package has completed."
+
+_refresh_docs *args="":
+    @echo
+    @echo -e "🏃 starting the refresh of the {{ITALIC}}documents{{RESET}} in {{BOLD}}{{PACKAGE}}{{RESET}}"
+    @PROMPT="$(cat ../.ai/prompt/refresh_documentation.md)\n\n## Task\n Your task is to orchestrate the update of all of the following documents: $(just readme_files) {{DOCS}} {{args}} based on changes you've discovered in the source code.\n\n" && just _claude "${PROMPT}"
+
+_refresh_skill:
+    @echo
+    @echo -e "🏃 starting the update of the {{ITALIC}}skill files{{RESET}} for {{BOLD}}{{PACKAGE}}{{RESET}}"
+
+refresh_skill:
+    @echo
+    @echo -e "Refreshing the {{BOLD}}{{LIBRARY}}{{RESET}} {{BLUE}}skill{{RESET}}"
+    @echo
+    @echo -e "- this will be done by updating all of the README.md files in the repo ({{DIM}}{{ITALIC}}as well as any files{{RESET}}"
+    @echo -e "  {{DIM}}{{ITALIC}}passed in by caller{{RESET}})"
+    @echo -e "- once the {{ITALIC}}drift{{RESET}} of the documentation files has been eliminated we'll rework the {{BOLD}}skill{{RESET}} files"
+    @echo -e "- as a final step, we'll look at whether the {{BOLD}}CLAUDE.md{{RESET}} file would benefit from being updated"
+    @echo -e "  based on the changes made"
+    @just _refresh_docs
+    @just _refresh_skill
 
 
+# No-op recipe: reference color vars so linters won't report them as unused.
+# Run `just _colors` if you want to exercise this (it does nothing).
+_colors:
+    @: {{BOLD}} {{ITALIC}} {{RESET}} {{BLACK}} {{RED}} {{GREEN}} {{YELLOW}} {{BLUE}} {{MAGENTA}} {{CYAN}} {{WHITE}} {{DIM}} >/dev/null || true
